
name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.vars.outputs.tag }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Get the version
        id: vars
        run: echo "tag=${GITHUB_SHA:10}" >> $GITHUB_OUTPUT

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" docker.io

      - name: Build Docker image with commit tag
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPO_NAME }}:${{ needs.build.outputs.tag }}

      - name: Push Docker image with commit tag
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPO_NAME }}:${{ needs.build.outputs.tag }}

      - name: Build Docker image with latest tag
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPO_NAME }}:latest

      - name: Push Docker image with latest tag
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPO_NAME }}:latest

# OLD VERSION, WHICH WORKED, JUST COMMENTED OUT HERE TO CHECK IF NEW VERSION WORKS
# name: Java CI with Gradle

# on:
#   push:   
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4
#     - name: Set up JDK 17
#       uses: actions/setup-java@v4
#       with:
#         java-version: '17'
#         distribution: 'temurin'
#     - name: Grant execute permission for gradlew
#       run: chmod +x gradlew
#     - name: Build with Gradle
#       run: ./gradlew clean build
#     - name: Get the version
#       id: vars
#       run: echo ::set-output name=tag::$(echo ${GITHUB_SHA:10})
#     - name: Docker login
#       env:
#         DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
#         DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
#       run : docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" docker.io
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.REPO_NAME}}:${{steps.vars.outputs.tag}}
#     - name: Publish dockerimage to docker hub
#       run: docker push ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.REPO_NAME}}:${{steps.vars.outputs.tag}}
#     - name: Build Docker image with latest tag
#       run: docker build . --file Dockerfile --tag ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.REPO_NAME}}:latest
#     - name: Publish dockerimage to docker hub
#       run: docker push ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.REPO_NAME}}:latest
